import {
  LayoutDashboard, Users, UserCheck, UserX, UsersRound, Shield, KeyRound, History, Smartphone, Activity,
  Building2, Hospital, TestTube, ScanLine, Pill, Plus, FileCheck2, FileText, Award, Layers, Clock, GitBranch,
  Images, Star, Heart, Gauge, CreditCard, ClipboardList,
  Stethoscope, GraduationCap, Briefcase, CalendarClock, CalendarCheck2, TrendingUp,
  Calendar, CalendarDays, CheckCircle2, XCircle, AlertTriangle, Zap, QrCode, CalendarRange,
  Beaker, FlaskConical, Package, Truck, Loader2, FileDown, FolderOpen, DollarSign,
  Radiation, Upload, Download, Image as ImageIcon,
  Pill as PillIcon, Store, Contact, ShoppingCart,
  FileHeart, Files, Archive, Lock,
  Bell, BellRing, Megaphone, Rocket, Siren, Send, MessageSquare, Mail, FileCode,
  Sparkles, Crown, Flame, Store as StoreIcon, Compass,
  LayoutGrid, MousePointer2, ToggleLeft, ArrowUpDown, Type, Palette, Eye, Play,
  Film, Video, PartyPopper, Calendar as Cal2, Target, MousePointerClick, BarChart3,
  Gift, Percent, Ticket, HeartPulse, Timer,
  Star as StarIcon, MessageCircle, Flag, PieChart,
  UserPlus, TrendingDown, Trophy,
  LineChart, BarChart2, Repeat, Award as AwardIcon, MapPin, Wallet,
  Brain, Cpu, Sparkle, Layers3, Settings2,
  Gem, Medal, ReceiptText, Calendar as Cal3, XOctagon,
  Banknote, Undo2, Receipt, Coins, FileSpreadsheet, Calculator,
  Inbox, Radio, MailPlus,
  FolderTree, File, FileImage, Video as Vid, FileText as Ft, Database, HardDrive,
  ShieldCheck, ShieldAlert, ShieldX, FileSignature, BadgeCheck,
  Map, Navigation, Route, Ruler,
  Languages, Globe2, Flag as FlagIcon, Clock3, Coins as Coin2,
  Settings, Info, Image as Img, Home, Search, MessageSquareText,
  Fingerprint, KeySquare, Timer as Timer2, Users2,
  UploadCloud, Save, RotateCcw, CalendarClock as CC,
  Webhook, Wrench, Server, Database as Db, Cloud, RefreshCw,
  BookOpen, MessageCircleQuestion, Bug, Lightbulb, LifeBuoy,
  User, LogOut, Key,
  type LucideIcon,
} from "lucide-react";

export type MenuItem = {
  id: string;
  title: string;
  icon?: LucideIcon;
  to?: string;                // resolved route
  soon?: boolean;             // no dedicated page yet -> /admin/soon
  badgeKey?: string;          // key into counters map
  children?: MenuItem[];
};

export type MenuSection = {
  id: string;
  title: string;
  icon: LucideIcon;
  items: MenuItem[];
};

// helper: link to /admin/soon?t=Title
const soon = (id: string, title: string, icon?: LucideIcon): MenuItem => ({ id, title, icon, soon: true });
const link = (id: string, title: string, to: string, icon?: LucideIcon, badgeKey?: string): MenuItem => ({ id, title, to, icon, badgeKey });

export const ADMIN_MENU: MenuSection[] = [
  {
    id: "dashboard", title: "الرئيسية", icon: LayoutDashboard,
    items: [
      link("overview", "نظرة عامة", "/admin", LayoutDashboard),
      link("live", "الإحصائيات المباشرة", "/admin/analytics", Activity),
      soon("quick", "إجراءات سريعة", Zap),
      link("recent", "أحدث الأنشطة", "/admin/audit", History),
      soon("health", "صحة النظام", HeartPulse),
      soon("server", "حالة الخوادم", Server),
      link("notif-latest", "أحدث الإشعارات", "/admin/notifications", Bell),
    ],
  },
  {
    id: "users", title: "إدارة المستخدمين", icon: Users,
    items: [
      link("users-all", "جميع المستخدمين", "/admin/users", Users, "users"),
      soon("users-patients", "المرضى", UserCheck),
      soon("users-family", "حسابات العائلة", UsersRound),
      soon("users-blocked", "المحظورون", UserX),
      soon("users-verified", "الموثّقون", BadgeCheck),
      soon("users-groups", "مجموعات المستخدمين", Users2),
      link("users-roles", "الأدوار", "/admin/permissions", Shield),
      link("users-perms", "الصلاحيات", "/admin/permissions", KeyRound),
      soon("users-login", "سجل الدخول", History),
      soon("users-sessions", "جلسات الأجهزة", Smartphone),
      link("users-activity", "سجل النشاط", "/admin/audit", Activity),
    ],
  },
  {
    id: "providers", title: "المنشآت الصحية", icon: Building2,
    items: [
      link("prov-all", "كل المنشآت", "/admin/facilities", Building2, "providers"),
      { id: "prov-types", title: "الأنواع", icon: Layers, children: [
        soon("prov-clinics", "العيادات", Stethoscope),
        soon("prov-hospitals", "المستشفيات", Hospital),
        soon("prov-labs", "المختبرات", TestTube),
        soon("prov-rad", "مراكز الأشعة", ScanLine),
        soon("prov-pharm", "الصيدليات", Pill),
      ]},
      { id: "prov-mgmt", title: "الإدارة", icon: Settings2, children: [
        soon("prov-add", "إضافة منشأة", Plus),
        soon("prov-edit", "تعديل المنشآت", FileText),
        link("prov-verify", "التحقق من المنشآت", "/admin/verification", FileCheck2, "verification"),
        soon("prov-docs", "المستندات", FileText),
        soon("prov-lic", "التراخيص", Award),
        link("prov-cat", "التصنيفات", "/admin/specialties", Layers),
        soon("prov-hours", "ساعات العمل", Clock),
        soon("prov-branches", "الفروع", GitBranch),
        soon("prov-gallery", "المعرض", Images),
        soon("prov-reviews", "التقييمات", Star),
        soon("prov-followers", "المتابعون", Heart),
        soon("prov-perf", "الأداء", Gauge),
        link("prov-subs", "الاشتراكات", "/admin/subscriptions", CreditCard),
        soon("prov-logs", "سجل النشاط", ClipboardList),
      ]},
    ],
  },
  {
    id: "doctors", title: "إدارة الأطباء", icon: Stethoscope,
    items: [
      link("doc-all", "جميع الأطباء", "/admin/doctors", Stethoscope, "doctors"),
      soon("doc-add", "إضافة طبيب", Plus),
      link("doc-spec", "التخصصات", "/admin/specialties", Layers),
      soon("doc-verify", "توثيق الأطباء", BadgeCheck),
      soon("doc-qual", "المؤهلات", GraduationCap),
      soon("doc-exp", "الخبرات", Briefcase),
      soon("doc-sched", "جدول العمل", CalendarClock),
      soon("doc-slots", "المواعيد المتاحة", CalendarCheck2),
      soon("doc-rev", "تقييمات الأطباء", Star),
      soon("doc-feat", "أطباء مميزون", Crown),
      soon("doc-followers", "المتابعون", Heart),
      soon("doc-perf", "الأداء", TrendingUp),
    ],
  },
  {
    id: "appointments", title: "إدارة المواعيد", icon: Calendar,
    items: [
      link("appt-all", "كل الحجوزات", "/admin/bookings", Calendar, "bookings"),
      soon("appt-today", "حجوزات اليوم", CalendarDays),
      soon("appt-upcoming", "القادمة", CalendarRange),
      soon("appt-pending", "قيد الانتظار", Clock),
      soon("appt-confirmed", "مؤكدة", CheckCircle2),
      soon("appt-completed", "مكتملة", CheckCircle2),
      soon("appt-cancelled", "ملغاة", XCircle),
      soon("appt-noshow", "لم يحضر", AlertTriangle),
      soon("appt-emergency", "طوارئ", Zap),
      link("appt-qr", "التحقق بالـQR", "/admin/qr", QrCode),
      soon("appt-cal", "عرض التقويم", Calendar),
      soon("appt-daily", "جدول يومي", CalendarDays),
      soon("appt-weekly", "جدول أسبوعي", CalendarRange),
      soon("appt-monthly", "جدول شهري", CalendarClock),
      link("appt-reports", "تقارير المواعيد", "/admin/reports", FileText),
    ],
  },
  {
    id: "lab", title: "وحدة المختبرات", icon: FlaskConical,
    items: [
      soon("lab-dash", "لوحة المختبرات", LayoutDashboard),
      soon("lab-svc", "خدمات المختبر", Beaker),
      soon("lab-book", "الحجوزات", Calendar),
      soon("lab-collect", "جمع العينات", Truck),
      soon("lab-queue", "قائمة المعالجة", Loader2),
      soon("lab-results", "نتائج الفحوصات", FileText),
      soon("lab-pdf", "تقارير PDF", FileDown),
      soon("lab-files", "الملفات الطبية", FolderOpen),
      soon("lab-staff", "موظفو المختبر", Users),
      soon("lab-rev", "تقارير الإيرادات", DollarSign),
    ],
  },
  {
    id: "radiology", title: "مراكز الأشعة", icon: Radiation,
    items: [
      soon("rad-dash", "لوحة الأشعة", LayoutDashboard),
      soon("rad-svc", "خدمات التصوير", ScanLine),
      soon("rad-appts", "المواعيد", Calendar),
      soon("rad-upload", "رفع الصور", Upload),
      soon("rad-reports", "التقارير", FileText),
      soon("rad-images", "الصور الطبية", ImageIcon),
      soon("rad-download", "مركز التحميل", Download),
      soon("rad-staff", "الموظفون", Users),
      soon("rad-rev", "تقارير الإيرادات", DollarSign),
    ],
  },
  {
    id: "pharmacy", title: "الصيدليات", icon: PillIcon,
    items: [
      soon("ph-dash", "لوحة الصيدليات", LayoutDashboard),
      soon("ph-all", "الصيدليات", Store),
      soon("ph-duty", "صيدليات المناوبة", Timer),
      soon("ph-meds", "الأدوية (لاحقاً)", Package),
      soon("ph-hours", "ساعات العمل", Clock),
      soon("ph-contact", "إدارة التواصل", Contact),
      soon("ph-orders", "الطلبات (لاحقاً)", ShoppingCart),
      soon("ph-rev", "تقارير الإيرادات", DollarSign),
    ],
  },
  {
    id: "records", title: "السجلات الطبية", icon: FileHeart,
    items: [
      soon("rec-rx", "الوصفات الطبية", FileHeart),
      soon("rec-lab", "تقارير المختبر", FlaskConical),
      soon("rec-rad", "تقارير الأشعة", Radiation),
      soon("rec-docs", "الوثائق الطبية", FileText),
      soon("rec-patient", "ملفات المرضى", Files),
      soon("rec-uploaded", "الملفات المرفوعة", UploadCloud),
      soon("rec-download", "مركز التحميل", Download),
      soon("rec-archive", "الأرشيف الآمن", Archive),
    ],
  },
  {
    id: "notifications", title: "مركز الإشعارات", icon: Bell,
    items: [
      link("notif-all", "كل الإشعارات", "/admin/notifications", Bell, "notifs"),
      soon("notif-appt", "إشعارات المواعيد", CalendarClock),
      soon("notif-promo", "العروض", Gift),
      soon("notif-camp", "الحملات", Megaphone),
      soon("notif-emg", "تنبيهات الطوارئ", Siren),
      soon("notif-push", "إشعارات Push", BellRing),
      soon("notif-sms", "رسائل SMS", MessageSquare),
      soon("notif-wa", "واتساب", Send),
      soon("notif-email", "البريد الإلكتروني", Mail),
      soon("notif-tmpl", "قوالب الإشعارات", FileCode),
    ],
  },
  {
    id: "featured", title: "المحتوى المميز", icon: Sparkles,
    items: [
      soon("ft-clinics", "عيادات مميزة", Stethoscope),
      soon("ft-hosp", "مستشفيات مميزة", Hospital),
      soon("ft-labs", "مختبرات مميزة", TestTube),
      soon("ft-rad", "أشعة مميزة", ScanLine),
      soon("ft-ph", "صيدليات مميزة", Pill),
      soon("ft-doc", "أطباء مميزون", Crown),
      soon("ft-top", "الأعلى تقييماً", Trophy),
      soon("ft-trend", "الأكثر رواجاً", Flame),
      soon("ft-open", "مفتوح الآن", StoreIcon),
      soon("ft-followed", "الأكثر متابعة", Heart),
      soon("ft-sponsor", "منشآت مموّلة", Rocket),
      soon("ft-new", "منشآت جديدة", Sparkle),
      soon("ft-manual", "تمييز يدوي", MousePointer2),
      link("ft-auto", "قواعد التمييز التلقائية", "/admin/smart", Compass),
    ],
  },
  {
    id: "home", title: "بناء الشاشة الرئيسية", icon: Home,
    items: [
      link("home-sections", "أقسام الرئيسية", "/admin/home", LayoutGrid),
      soon("home-dnd", "سحب وإفلات", MousePointer2),
      soon("home-toggle", "تفعيل / تعطيل", ToggleLeft),
      soon("home-order", "ترتيب الأقسام", ArrowUpDown),
      soon("home-titles", "عناوين مخصّصة", Type),
      soon("home-icons", "الأيقونات", Sparkles),
      link("home-theme", "ألوان الثيم", "/admin/ui", Palette),
      soon("home-visib", "الظهور", Eye),
      soon("home-preview", "معاينة مباشرة", Play),
      soon("home-publish", "نشر التغييرات", UploadCloud),
    ],
  },
  {
    id: "banners", title: "إدارة البانرات", icon: Film,
    items: [
      link("ban-img", "بانرات الصور", "/admin/ads", ImageIcon, "ads"),
      soon("ban-vid", "بانرات فيديو", Video),
      soon("ban-aware", "حملات توعية", PartyPopper),
      soon("ban-season", "موسمية", Cal2),
      soon("ban-spons", "إعلانات مموّلة", Target),
      soon("ban-sched", "الجدولة", CalendarClock),
      soon("ban-pos", "مواقع العرض", LayoutGrid),
      soon("ban-click", "وجهات النقر", MousePointerClick),
      soon("ban-stats", "إحصاءات البانرات", BarChart3),
    ],
  },
  {
    id: "offers", title: "العروض والحملات", icon: Gift,
    items: [
      link("of-all", "العروض", "/admin/offers", Gift, "offers"),
      soon("of-disc", "الخصومات", Percent),
      soon("of-coup", "الكوبونات", Ticket),
      soon("of-health", "حملات صحية", HeartPulse),
      soon("of-aware", "حملات توعية", PartyPopper),
      soon("of-spons", "حملات مموّلة", Rocket),
      soon("of-sched", "الجدولة", CalendarClock),
      soon("of-exp", "قواعد الانتهاء", Timer),
    ],
  },
  {
    id: "reviews", title: "التقييمات والمراجعات", icon: StarIcon,
    items: [
      soon("rv-prov", "تقييمات المنشآت", Building2),
      soon("rv-doc", "تقييمات الأطباء", Stethoscope),
      soon("rv-pend", "قيد المراجعة", MessageCircle),
      soon("rv-flag", "بلاغات", Flag),
      soon("rv-stats", "تحليلات التقييمات", PieChart),
      soon("rv-abuse", "بلاغات الإساءة", ShieldAlert),
    ],
  },
  {
    id: "follows", title: "المتابعون والمفضلة", icon: Heart,
    items: [
      soon("fl-prov", "متابعو المنشآت", Building2),
      soon("fl-doc", "متابعو الأطباء", Stethoscope),
      soon("fl-most", "الأكثر متابعة", Trophy),
      soon("fl-fav", "مفضلات المستخدمين", Heart),
      soon("fl-trend", "المفضلات الرائجة", Flame),
    ],
  },
  {
    id: "analytics", title: "مركز التحليلات", icon: BarChart3,
    items: [
      link("an-live", "اللوحة المباشرة", "/admin/analytics", Activity),
      { id: "an-book", title: "الحجوزات", icon: Calendar, children: [
        soon("an-b-d", "يومي", CalendarDays),
        soon("an-b-w", "أسبوعي", CalendarRange),
        soon("an-b-m", "شهري", CalendarClock),
        soon("an-b-y", "سنوي", Calendar),
      ]},
      { id: "an-users", title: "المستخدمون", icon: Users, children: [
        soon("an-u-g", "النمو", TrendingUp),
        soon("an-u-a", "النشطون", UserPlus),
        soon("an-u-r", "الاحتفاظ", Repeat),
      ]},
      { id: "an-prov", title: "المنشآت", icon: Building2, children: [
        soon("an-p-perf", "الأداء", LineChart),
        soon("an-p-rank", "الترتيب", Trophy),
        soon("an-p-view", "الأكثر مشاهدة", Eye),
        soon("an-p-book", "الأكثر حجزاً", CalendarCheck2),
      ]},
      { id: "an-rev", title: "الإيرادات", icon: DollarSign, children: [
        link("an-r-rep", "تقارير الإيرادات", "/admin/finance", ReceiptText),
        link("an-r-sub", "إيراد الاشتراكات", "/admin/subscriptions", CreditCard),
        soon("an-r-ads", "إيراد الإعلانات", BarChart2),
      ]},
      { id: "an-med", title: "التحليلات الطبية", icon: HeartPulse, children: [
        soon("an-m-spec", "أشهر التخصصات", AwardIcon),
        soon("an-m-svc", "أشهر الخدمات", Star),
        soon("an-m-geo", "الجغرافية", MapPin),
      ]},
    ],
  },
  {
    id: "ai", title: "إدارة الذكاء الاصطناعي", icon: Brain,
    items: [
      link("ai-assist", "المساعد الصحي", "/admin/ai", Brain),
      soon("ai-reco", "محرك التوصيات", Sparkle),
      link("ai-rank", "الترتيب الذكي", "/admin/smart", Compass),
      soon("ai-score", "تسجيل التمييز", Trophy),
      soon("ai-sugg", "الاقتراحات", Lightbulb),
      soon("ai-logs", "سجلات AI", FileText),
      soon("ai-learn", "إعدادات التعلم", Cpu),
    ],
  },
  {
    id: "plans", title: "خطط الاشتراك", icon: Gem,
    items: [
      link("pl-all", "الخطط", "/admin/packages", Layers3),
      soon("pl-free", "المجاني", Wallet),
      soon("pl-silver", "الفضي", Medal),
      soon("pl-gold", "الذهبي", Crown),
      soon("pl-diamond", "الماسي", Gem),
      soon("pl-feat", "مزايا الخطط", Sparkles),
      link("pl-subs", "اشتراكات المنشآت", "/admin/subscriptions", CreditCard),
      soon("pl-renew", "التجديدات", Repeat),
      soon("pl-exp", "المنتهية", XOctagon),
      link("pl-pay", "سجل المدفوعات", "/admin/payments", ReceiptText),
    ],
  },
  {
    id: "finance", title: "المركز المالي", icon: Banknote,
    items: [
      link("fn-txn", "المعاملات", "/admin/payments", ReceiptText, "payments"),
      link("fn-pay", "المدفوعات", "/admin/payments", CreditCard),
      soon("fn-ref", "المرتجعات", Undo2),
      soon("fn-inv", "الفواتير", Receipt),
      link("fn-rev", "الإيرادات", "/admin/finance", Coins),
      link("fn-rep", "تقارير مالية", "/admin/reports", FileSpreadsheet),
      soon("fn-tax", "الضرائب", Calculator),
      soon("fn-exp", "تصدير التقارير", FileDown),
    ],
  },
  {
    id: "msg", title: "مركز الرسائل", icon: Inbox,
    items: [
      soon("msg-in", "صندوق الوارد", Inbox),
      soon("msg-broad", "بث جماعي", Radio),
      soon("msg-int", "رسائل داخلية", MessageSquareText),
      soon("msg-prov", "رسائل المنشآت", Building2),
      soon("msg-pat", "رسائل المرضى", Users),
      soon("msg-tmpl", "القوالب", FileCode),
      soon("msg-sched", "مجدولة", MailPlus),
    ],
  },
  {
    id: "files", title: "مدير الملفات", icon: FolderTree,
    items: [
      soon("fi-img", "الصور", FileImage),
      soon("fi-docs", "المستندات", Ft),
      soon("fi-med", "الملفات الطبية", FileHeart),
      soon("fi-vid", "الفيديو", Vid),
      soon("fi-pdf", "PDFs", File),
      soon("fi-usage", "استخدام التخزين", Database),
      soon("fi-backup", "ملفات النسخ", HardDrive),
    ],
  },
  {
    id: "verify", title: "مركز التوثيق", icon: ShieldCheck,
    items: [
      link("vr-pend", "بانتظار التوثيق", "/admin/verification", ShieldAlert, "verification"),
      link("vr-appr", "الموثّقون", "/admin/verification", ShieldCheck),
      link("vr-rej", "المرفوضون", "/admin/verification", ShieldX),
      soon("vr-docs", "وثائق التوثيق", FileSignature),
      soon("vr-lic", "التحقق من التراخيص", BadgeCheck),
      soon("vr-hist", "سجل التوثيق", History),
    ],
  },
  {
    id: "maps", title: "الخرائط والمواقع", icon: Map,
    items: [
      link("mp-cities", "المدن", "/admin/cities", MapPin),
      soon("mp-areas", "المناطق", Navigation),
      soon("mp-gps", "إعدادات GPS", Route),
      soon("mp-loc", "مواقع المنشآت", Building2),
      soon("mp-cov", "تغطية الخدمة", Map),
      soon("mp-dist", "قواعد المسافة", Ruler),
    ],
  },
  {
    id: "i18n", title: "التوطين", icon: Languages,
    items: [
      soon("lo-lang", "اللغات", Languages),
      soon("lo-tr", "إدارة الترجمة", Type),
      soon("lo-country", "الدول", Globe2),
      soon("lo-region", "المناطق", FlagIcon),
      soon("lo-tz", "المناطق الزمنية", Clock3),
      soon("lo-cur", "العملات", Coin2),
      soon("lo-date", "تنسيق التواريخ", Calendar),
    ],
  },
  {
    id: "system", title: "إعدادات النظام", icon: Settings,
    items: [
      { id: "sy-gen", title: "عام", icon: Info, children: [
        link("sy-info", "معلومات المنصة", "/admin/settings", Info),
        soon("sy-name", "اسم المنصة", Type),
        soon("sy-logo", "الشعار", Img),
        soon("sy-fav", "أيقونة المتصفح", Sparkles),
        soon("sy-splash", "شاشة البدء", Sparkle),
        soon("sy-contact", "معلومات التواصل", Contact),
      ]},
      { id: "sy-app", title: "التطبيق", icon: Smartphone, children: [
        soon("sy-mobile", "إعدادات التطبيق", Smartphone),
        link("sy-home", "الرئيسية", "/admin/home", Home),
        soon("sy-book", "الحجوزات", Calendar),
        soon("sy-notif", "الإشعارات", Bell),
        soon("sy-search", "البحث", Search),
        soon("sy-review", "التقييمات", Star),
        link("sy-ai", "الذكاء الاصطناعي", "/admin/ai", Brain),
      ]},
      { id: "sy-auth", title: "المصادقة", icon: Fingerprint, children: [
        soon("sy-login", "طرق الدخول", KeySquare),
        soon("sy-otp", "OTP", Key),
        soon("sy-pw", "سياسة كلمة السر", Lock),
        soon("sy-timeout", "انتهاء الجلسة", Timer2),
        soon("sy-devices", "حدود الأجهزة", Smartphone),
      ]},
      { id: "sy-media", title: "الوسائط", icon: ImageIcon, children: [
        soon("sy-imgs", "الصور", FileImage),
        soon("sy-vids", "الفيديو", Video),
        soon("sy-lim", "حدود الرفع", UploadCloud),
        soon("sy-storage", "التخزين", HardDrive),
      ]},
      { id: "sy-comm", title: "البريد والرسائل", icon: Mail, children: [
        soon("sy-smtp", "SMTP", Mail),
        soon("sy-sms", "بوابة SMS", MessageSquare),
        soon("sy-wa", "WhatsApp API", Send),
        soon("sy-push", "Push API", BellRing),
      ]},
      { id: "sy-sec", title: "الأمن", icon: Shield, children: [
        link("sy-roles", "الأدوار", "/admin/permissions", Shield),
        link("sy-perms", "الصلاحيات", "/admin/permissions", KeyRound),
        soon("sy-api", "مفاتيح API", Key),
        soon("sy-enc", "التشفير", Lock),
        soon("sy-fw", "جدار الحماية", ShieldAlert),
        link("sy-seclog", "سجلات الأمن", "/admin/audit", FileText),
      ]},
      { id: "sy-perf", title: "الأداء", icon: Gauge, children: [
        soon("sy-cache", "الكاش", Database),
        soon("sy-queue", "الطوابير", Loader2),
        soon("sy-cdn", "CDN", Cloud),
        soon("sy-opt", "التحسين", Sparkles),
      ]},
      { id: "sy-bk", title: "النسخ الاحتياطي", icon: Save, children: [
        link("sy-bk-man", "نسخ يدوي", "/admin/backup", Save),
        soon("sy-bk-auto", "نسخ تلقائي", RefreshCw),
        soon("sy-bk-res", "استعادة النظام", RotateCcw),
        soon("sy-bk-sched", "جدولة النسخ", CC),
      ]},
      { id: "sy-dev", title: "المطورون", icon: Wrench, children: [
        soon("sy-api-mgmt", "إدارة API", Server),
        soon("sy-webhook", "Webhooks", Webhook),
        link("sy-logs", "السجلات", "/admin/audit", FileText),
        soon("sy-int", "التكاملات", Db),
        soon("sy-maint", "وضع الصيانة", Wrench),
      ]},
    ],
  },
  {
    id: "audit", title: "سجلات التدقيق", icon: History,
    items: [
      link("au-login", "سجل الدخول", "/admin/audit", KeySquare),
      link("au-act", "سجل النشاط", "/admin/audit", Activity),
      link("au-sec", "سجلات الأمن", "/admin/audit", Shield),
      soon("au-prov", "سجل المنشآت", Building2),
      soon("au-admin", "سجل المشرفين", Crown),
      soon("au-api", "سجل API", Server),
      soon("au-err", "سجل الأخطاء", Bug),
      soon("au-exp", "تصدير السجلات", FileDown),
    ],
  },
  {
    id: "support", title: "مركز الدعم", icon: LifeBuoy,
    items: [
      link("sp-tix", "تذاكر الدعم", "/admin/support", LifeBuoy, "tickets"),
      soon("sp-chat", "الدردشة المباشرة", MessageCircle),
      soon("sp-faq", "الأسئلة الشائعة", MessageCircleQuestion),
      soon("sp-kb", "قاعدة المعرفة", BookOpen),
      soon("sp-fb", "التغذية الراجعة", MessageSquare),
      soon("sp-bug", "بلاغات الأخطاء", Bug),
      soon("sp-req", "طلبات المزايا", Lightbulb),
    ],
  },
  {
    id: "account", title: "الحساب", icon: User,
    items: [
      link("ac-me", "ملفي الشخصي", "/profile", User),
      link("ac-set", "إعدادات الحساب", "/admin/settings", Settings),
      soon("ac-pw", "تغيير كلمة السر", KeyRound),
      soon("ac-2fa", "التحقق بخطوتين", Fingerprint),
      soon("ac-sess", "الجلسات النشطة", Smartphone),
      link("ac-logout", "تسجيل الخروج", "/auth", LogOut),
    ],
  },
];
