/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as BookProviderIdRouteImport } from './routes/book.$providerId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookProviderIdRoute = BookProviderIdRouteImport.update({
  id: '/book/$providerId',
  path: '/book/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/family': typeof FamilyRoute
  '/favorites': typeof FavoritesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/search': typeof SearchRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/provider/$id': typeof ProviderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/family': typeof FamilyRoute
  '/favorites': typeof FavoritesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/search': typeof SearchRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/provider/$id': typeof ProviderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/family': typeof FamilyRoute
  '/favorites': typeof FavoritesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/search': typeof SearchRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/provider/$id': typeof ProviderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/bookings'
    | '/dashboard'
    | '/family'
    | '/favorites'
    | '/notifications'
    | '/profile'
    | '/records'
    | '/search'
    | '/book/$providerId'
    | '/provider/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/bookings'
    | '/dashboard'
    | '/family'
    | '/favorites'
    | '/notifications'
    | '/profile'
    | '/records'
    | '/search'
    | '/book/$providerId'
    | '/provider/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/bookings'
    | '/dashboard'
    | '/family'
    | '/favorites'
    | '/notifications'
    | '/profile'
    | '/records'
    | '/search'
    | '/book/$providerId'
    | '/provider/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  DashboardRoute: typeof DashboardRoute
  FamilyRoute: typeof FamilyRoute
  FavoritesRoute: typeof FavoritesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RecordsRoute: typeof RecordsRoute
  SearchRoute: typeof SearchRoute
  BookProviderIdRoute: typeof BookProviderIdRoute
  ProviderIdRoute: typeof ProviderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$providerId': {
      id: '/book/$providerId'
      path: '/book/$providerId'
      fullPath: '/book/$providerId'
      preLoaderRoute: typeof BookProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  DashboardRoute: DashboardRoute,
  FamilyRoute: FamilyRoute,
  FavoritesRoute: FavoritesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RecordsRoute: RecordsRoute,
  SearchRoute: SearchRoute,
  BookProviderIdRoute: BookProviderIdRoute,
  ProviderIdRoute: ProviderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
