/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as MasterTokenRouteImport } from './routes/master.$token'
import { Route as DoctorIdRouteImport } from './routes/doctor.$id'
import { Route as DashboardReceptionRouteImport } from './routes/dashboard.reception'
import { Route as BookProviderIdRouteImport } from './routes/book.$providerId'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUiRouteImport } from './routes/admin.ui'
import { Route as AdminTokensRouteImport } from './routes/admin.tokens'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSpecialtiesRouteImport } from './routes/admin.specialties'
import { Route as AdminSoonRouteImport } from './routes/admin.soon'
import { Route as AdminSmartRouteImport } from './routes/admin.smart'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminQrRouteImport } from './routes/admin.qr'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPaymentMethodsRouteImport } from './routes/admin.payment-methods'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminFacilitiesRouteImport } from './routes/admin.facilities'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCitiesRouteImport } from './routes/admin.cities'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as PortalReceptionTokenRouteImport } from './routes/portal.reception.$token'
import { Route as PortalProviderTokenRouteImport } from './routes/portal.provider.$token'
import { Route as AdminProvidersIdRouteImport } from './routes/admin.providers.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const MasterTokenRoute = MasterTokenRouteImport.update({
  id: '/master/$token',
  path: '/master/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIdRoute = DoctorIdRouteImport.update({
  id: '/doctor/$id',
  path: '/doctor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReceptionRoute = DashboardReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => DashboardRoute,
} as any)
const BookProviderIdRoute = BookProviderIdRouteImport.update({
  id: '/book/$providerId',
  path: '/book/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUiRoute = AdminUiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTokensRoute = AdminTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpecialtiesRoute = AdminSpecialtiesRouteImport.update({
  id: '/specialties',
  path: '/specialties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSoonRoute = AdminSoonRouteImport.update({
  id: '/soon',
  path: '/soon',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmartRoute = AdminSmartRouteImport.update({
  id: '/smart',
  path: '/smart',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQrRoute = AdminQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentMethodsRoute = AdminPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacilitiesRoute = AdminFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalReceptionTokenRoute = PortalReceptionTokenRouteImport.update({
  id: '/portal/reception/$token',
  path: '/portal/reception/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProviderTokenRoute = PortalProviderTokenRouteImport.update({
  id: '/portal/provider/$token',
  path: '/portal/provider/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProvidersIdRoute = AdminProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/family': typeof FamilyRoute
  '/favorites': typeof FavoritesRoute
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/records': typeof RecordsRoute
  '/search': typeof SearchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/qr': typeof AdminQrRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/smart': typeof AdminSmartRoute
  '/admin/soon': typeof AdminSoonRoute
  '/admin/specialties': typeof AdminSpecialtiesRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/ui': typeof AdminUiRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/dashboard/reception': typeof DashboardReceptionRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/master/$token': typeof MasterTokenRoute
  '/profile/edit': typeof ProfileEditRoute
  '/provider/$id': typeof ProviderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/providers/$id': typeof AdminProvidersIdRoute
  '/portal/provider/$token': typeof PortalProviderTokenRoute
  '/portal/reception/$token': typeof PortalReceptionTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/family': typeof FamilyRoute
  '/favorites': typeof FavoritesRoute
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/records': typeof RecordsRoute
  '/search': typeof SearchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/qr': typeof AdminQrRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/smart': typeof AdminSmartRoute
  '/admin/soon': typeof AdminSoonRoute
  '/admin/specialties': typeof AdminSpecialtiesRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/ui': typeof AdminUiRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/dashboard/reception': typeof DashboardReceptionRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/master/$token': typeof MasterTokenRoute
  '/profile/edit': typeof ProfileEditRoute
  '/provider/$id': typeof ProviderIdRoute
  '/admin': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/providers/$id': typeof AdminProvidersIdRoute
  '/portal/provider/$token': typeof PortalProviderTokenRoute
  '/portal/reception/$token': typeof PortalReceptionTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/family': typeof FamilyRoute
  '/favorites': typeof FavoritesRoute
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/records': typeof RecordsRoute
  '/search': typeof SearchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/qr': typeof AdminQrRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/smart': typeof AdminSmartRoute
  '/admin/soon': typeof AdminSoonRoute
  '/admin/specialties': typeof AdminSpecialtiesRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/ui': typeof AdminUiRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/dashboard/reception': typeof DashboardReceptionRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/master/$token': typeof MasterTokenRoute
  '/profile/edit': typeof ProfileEditRoute
  '/provider/$id': typeof ProviderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/providers/$id': typeof AdminProvidersIdRoute
  '/portal/provider/$token': typeof PortalProviderTokenRoute
  '/portal/reception/$token': typeof PortalReceptionTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/bookings'
    | '/dashboard'
    | '/family'
    | '/favorites'
    | '/mcp'
    | '/notifications'
    | '/profile'
    | '/records'
    | '/search'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ads'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/bookings'
    | '/admin/cities'
    | '/admin/content'
    | '/admin/doctors'
    | '/admin/facilities'
    | '/admin/finance'
    | '/admin/home'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/packages'
    | '/admin/payment-methods'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/qr'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/smart'
    | '/admin/soon'
    | '/admin/specialties'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/tokens'
    | '/admin/ui'
    | '/admin/users'
    | '/admin/verification'
    | '/book/$providerId'
    | '/dashboard/reception'
    | '/doctor/$id'
    | '/master/$token'
    | '/profile/edit'
    | '/provider/$id'
    | '/admin/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/providers/$id'
    | '/portal/provider/$token'
    | '/portal/reception/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/bookings'
    | '/dashboard'
    | '/family'
    | '/favorites'
    | '/mcp'
    | '/notifications'
    | '/profile'
    | '/records'
    | '/search'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ads'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/bookings'
    | '/admin/cities'
    | '/admin/content'
    | '/admin/doctors'
    | '/admin/facilities'
    | '/admin/finance'
    | '/admin/home'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/packages'
    | '/admin/payment-methods'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/qr'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/smart'
    | '/admin/soon'
    | '/admin/specialties'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/tokens'
    | '/admin/ui'
    | '/admin/users'
    | '/admin/verification'
    | '/book/$providerId'
    | '/dashboard/reception'
    | '/doctor/$id'
    | '/master/$token'
    | '/profile/edit'
    | '/provider/$id'
    | '/admin'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/providers/$id'
    | '/portal/provider/$token'
    | '/portal/reception/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/bookings'
    | '/dashboard'
    | '/family'
    | '/favorites'
    | '/mcp'
    | '/notifications'
    | '/profile'
    | '/records'
    | '/search'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ads'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/bookings'
    | '/admin/cities'
    | '/admin/content'
    | '/admin/doctors'
    | '/admin/facilities'
    | '/admin/finance'
    | '/admin/home'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/packages'
    | '/admin/payment-methods'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/qr'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/smart'
    | '/admin/soon'
    | '/admin/specialties'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/tokens'
    | '/admin/ui'
    | '/admin/users'
    | '/admin/verification'
    | '/book/$providerId'
    | '/dashboard/reception'
    | '/doctor/$id'
    | '/master/$token'
    | '/profile/edit'
    | '/provider/$id'
    | '/admin/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/providers/$id'
    | '/portal/provider/$token'
    | '/portal/reception/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FamilyRoute: typeof FamilyRoute
  FavoritesRoute: typeof FavoritesRoute
  McpRoute: typeof McpRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RecordsRoute: typeof RecordsRoute
  SearchRoute: typeof SearchRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BookProviderIdRoute: typeof BookProviderIdRoute
  DoctorIdRoute: typeof DoctorIdRoute
  MasterTokenRoute: typeof MasterTokenRoute
  ProviderIdRoute: typeof ProviderIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  PortalProviderTokenRoute: typeof PortalProviderTokenRoute
  PortalReceptionTokenRoute: typeof PortalReceptionTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/master/$token': {
      id: '/master/$token'
      path: '/master/$token'
      fullPath: '/master/$token'
      preLoaderRoute: typeof MasterTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/$id': {
      id: '/doctor/$id'
      path: '/doctor/$id'
      fullPath: '/doctor/$id'
      preLoaderRoute: typeof DoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reception': {
      id: '/dashboard/reception'
      path: '/reception'
      fullPath: '/dashboard/reception'
      preLoaderRoute: typeof DashboardReceptionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/book/$providerId': {
      id: '/book/$providerId'
      path: '/book/$providerId'
      fullPath: '/book/$providerId'
      preLoaderRoute: typeof BookProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ui': {
      id: '/admin/ui'
      path: '/ui'
      fullPath: '/admin/ui'
      preLoaderRoute: typeof AdminUiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tokens': {
      id: '/admin/tokens'
      path: '/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AdminTokensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/specialties': {
      id: '/admin/specialties'
      path: '/specialties'
      fullPath: '/admin/specialties'
      preLoaderRoute: typeof AdminSpecialtiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/soon': {
      id: '/admin/soon'
      path: '/soon'
      fullPath: '/admin/soon'
      preLoaderRoute: typeof AdminSoonRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/smart': {
      id: '/admin/smart'
      path: '/smart'
      fullPath: '/admin/smart'
      preLoaderRoute: typeof AdminSmartRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/qr': {
      id: '/admin/qr'
      path: '/qr'
      fullPath: '/admin/qr'
      preLoaderRoute: typeof AdminQrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-methods': {
      id: '/admin/payment-methods'
      path: '/payment-methods'
      fullPath: '/admin/payment-methods'
      preLoaderRoute: typeof AdminPaymentMethodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facilities': {
      id: '/admin/facilities'
      path: '/facilities'
      fullPath: '/admin/facilities'
      preLoaderRoute: typeof AdminFacilitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cities': {
      id: '/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/reception/$token': {
      id: '/portal/reception/$token'
      path: '/portal/reception/$token'
      fullPath: '/portal/reception/$token'
      preLoaderRoute: typeof PortalReceptionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/provider/$token': {
      id: '/portal/provider/$token'
      path: '/portal/provider/$token'
      fullPath: '/portal/provider/$token'
      preLoaderRoute: typeof PortalProviderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/providers/$id': {
      id: '/admin/providers/$id'
      path: '/providers/$id'
      fullPath: '/admin/providers/$id'
      preLoaderRoute: typeof AdminProvidersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminFacilitiesRoute: typeof AdminFacilitiesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPaymentMethodsRoute: typeof AdminPaymentMethodsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminQrRoute: typeof AdminQrRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSmartRoute: typeof AdminSmartRoute
  AdminSoonRoute: typeof AdminSoonRoute
  AdminSpecialtiesRoute: typeof AdminSpecialtiesRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTokensRoute: typeof AdminTokensRoute
  AdminUiRoute: typeof AdminUiRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProvidersIdRoute: typeof AdminProvidersIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminAiRoute: AdminAiRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminFacilitiesRoute: AdminFacilitiesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPaymentMethodsRoute: AdminPaymentMethodsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminQrRoute: AdminQrRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSmartRoute: AdminSmartRoute,
  AdminSoonRoute: AdminSoonRoute,
  AdminSpecialtiesRoute: AdminSpecialtiesRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTokensRoute: AdminTokensRoute,
  AdminUiRoute: AdminUiRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProvidersIdRoute: AdminProvidersIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardReceptionRoute: typeof DashboardReceptionRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardReceptionRoute: DashboardReceptionRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FamilyRoute: FamilyRoute,
  FavoritesRoute: FavoritesRoute,
  McpRoute: McpRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RecordsRoute: RecordsRoute,
  SearchRoute: SearchRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BookProviderIdRoute: BookProviderIdRoute,
  DoctorIdRoute: DoctorIdRoute,
  MasterTokenRoute: MasterTokenRoute,
  ProviderIdRoute: ProviderIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  PortalProviderTokenRoute: PortalProviderTokenRoute,
  PortalReceptionTokenRoute: PortalReceptionTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
